### ISSUE TITLE
Пропадают файлы при загрузке более 10 вложений в диалог

### ISSUE THREAD

**Issue by suprunchuk** [Elorucov/Laney-Avalonia#25]
### Шаги для воспроизведения

1. **Перетащите более 10 фотографий** в диалоговое окно в качестве файлов. Например, выберите 12 изображений для загрузки.
2. **Отправьте сообщение** с 12 вложениями, нажав кнопку отправки.
3. **Наблюдайте за результатом**: из 12 загруженных файлов отправляется только 10, а остальные 2 пропадают без следа.

### Фактический результат

При попытке отправить более 10 вложений, все файлы, превышающие этот лимит, исчезают и не отображаются в диалоге.

### Ожидаемый результат

Система должна обрабатывать все вложения аналогично тому, как это реализовано на платформе `https://web.vk.me`, где дополнительные вложения отправляются в следующем сообщении, обеспечивая полную передачу всех файлов.

### Операционная система

Windows 11 Pro, версия 24H2

### Версия приложения Laney

v2.0.624-BETA

### Вложения (скриншоты)

![img-2024-10-30-23-16-56](https://github.com/user-attachments/assets/19a973c9-732a-4928-9e8e-48cca7016099)
---
![img-2024-10-30-23-20-32](https://github.com/user-attachments/assets/b133d5c3-60b3-4687-8fa3-c70672ed274e)
---

https://github.com/user-attachments/assets/af095839-ad6e-4db2-a2ca-7765bf99f7c2

**Comment by Elorucov** [comment]
Это нормальное поведение, пока что не планирую сделать отправку более 10 вложений за раз. Я только сделаю предупреждение в приложении.
