### ISSUE TITLE
Происходит ошибка подключение во время авторизации в VK ID.

### ISSUE THREAD

**Issue by rifat1998v** [Elorucov/Laney-Avalonia#28]
### Шаги для воспроизведения

1) Запустить приложение Laney на устройстве PC
2) Пройти авторизацию в VK ID приложении 

### Фактический результат

Во время авторизации мы замечаем ошибку подключения во время авторизации, в итоге мы не можем зайти в аккаунт VK ID дать разрешение на вход в VK ID через приложение.

### Ожидаемый результат

Авторизация проходит успешно.

### Операционная система

Windows 7 Ultimate sp1

### Версия приложения Laney

2.0.624

**Comment by rifat1998v** [comment]
Проблема была решена в течение нескольких минут после создания репорта или были неполадки в локалях программы

**Comment by Elorucov** [comment]
На самом деле это проблема в самом ВК, во время авторизации ВК иногда может куда-то терять порт. Т. е. в конце авторизации в адресной строке должно быть `localhost:52639#access_token=...`, но иногда теряется `:52639`.

**Comment by rifat1998v** [comment]
Возможно, благодарю за ответ.
Может ещё связан с первым запуском приложения, иногда авторизация не всегда срабатывает при первом запуске программы.
