### ISSUE TITLE
Краш клиента при переключении на сообщество

### ISSUE THREAD

**Issue by suprunchuk** [Elorucov/Laney-Avalonia#4]
### Шаги для воспроизведения

1. Откройте приложение и войдите в свою учетную запись.
2. Перейдите в раздел управления сообществами, нажав на иконку аватарки в верхнем углу экрана.
3. Выберите любое управляемое сообщество из списка и нажмите сохранить.
4. Нажмите на свой аватар и переключитесь на только что добавленное сообщество.

### Ожидаемый результат

Приложение должно корректно переключиться на страницу выбранного сообщества без возникновения ошибок или краша. Пользователь должен увидеть содержимое выбранного сообщества.

### Фактический результат

При попытке переключиться на выбранное сообщество приложение неожиданно закрывается, вызывая краш клиента. Актуально только если сообщество добавляется по новой. С уже добавленными ранее сообществами баг не воспроизводится.

### Операционная система

windows 11 pro

### Версия приложения Laney

2.0.600

### Логи

```shell
2024-08-14 14:00:49.849 +03:00 [INF] MainWindow initialized.
2024-08-14 14:00:49.849 +03:00 [INF] Init session (-226270912)
2024-08-14 14:00:49.883 +03:00 [INF] MainWindow activated. Launch time: 176 ms.
2024-08-14 14:00:50.006 +03:00 [FTL] App crashed! (UE)

System.NullReferenceException: Arg_NullReferenceException
   at laney!<BaseAddress>+0x76236e
--- End of stack trace from previous location ---
   at laney!<BaseAddress>+0xa09fa8
   at laney!<BaseAddress>+0xa4af74
   at laney!<BaseAddress>+0x10f01a
   at laney!<BaseAddress>+0x10e9fb
   at laney!<BaseAddress>+0x10d4a1
   at laney!<BaseAddress>+0x10d5e1
   at laney!<BaseAddress>+0x10d512
   at laney!<BaseAddress>+0x7eecdc
   at laney!<BaseAddress>+0x12cefd6
```

**Comment by rifat1998v** [comment]
Здравствуйте сейчас проблема снова актуальна во время клика на кнопку "Сохранить" выскакивает окно с ошибкой такого содержания "Arg_NullReferenceException (0x80004003)"
Чуть ниже кину логи с этой ошибкой.
