### ISSUE TITLE
Отображается онлайн у избранного

### ISSUE THREAD

**Issue by suprunchuk** [Elorucov/Laney-Avalonia#9]
### Шаги для воспроизведения

1. Пишет любое сообщение в избранное, чтобы чат появился в списке чатов.
2. Открываем главную - список чатов. Ищем избранное.

### Ожидаемый результат

У избранного не должно быть метки онлайна. 

### Фактический результат

У избранного отображается знак онлайна.
![2024-08-19_09-32-11](https://github.com/user-attachments/assets/520fbfed-38a7-4bc2-bf85-cda87858998e)

### Операционная система

win 11 pro

### Версия приложения Laney

v2.0.605-BETA

**Comment by Elorucov** [comment]
https://github.com/Elorucov/Laney-Avalonia/commit/6ba94e4d3faddea999cbc3fbc6928bca633423a2
https://github.com/Elorucov/Laney-Avalonia/commit/a0b6ccb6f73fdb64fa4a6f59e97b84723077af98
